name: 'Setup Zig'
description: 'Setup a Zig compiler and add it to the path'
branding:
  icon: play
  color: orange
author: 'goto-bus-stop'
inputs:
  version:
    description: 'Version of the zig compiler to use (must be 0.3.0 or up)'
    required: true
    default: 'master'
  cache:
    description: 'Cache downloaded compilers for faster action runs. Strongly recommended.'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
